### ISSUE TITLE
project_logging() returns "The value of the parameter "content" is not valid"

### ISSUE THREAD

**Issue by toujames** [epicentre-msf/redcap#2]
I ran this with:
`project_logging(conn)`

And R returns with the result:
`"The value of the parameter "content" is not valid"`

Is this not a vlid api call?

**Comment by patrickbarks** [comment]
Hmm, not sure. What version of REDCap are you using? I believe the export logging method is only available for REDCap 10.8.0 and later. You can check with `redcap::redcap_version(conn)`

**Comment by toujames** [comment]
Yep that's it. I'm running and old version of redcap.

```
> redcap::redcap_version(conn)
[1] "10.6.19"
```
